services:
  postgres:
    image: postgres:16-alpine
    container_name: minsy-postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-minsy_pgsql}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - minsy_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-minsy_pgsql}"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: minsy-redis-dev
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - minsy_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  minsy_pg_data:
  minsy_redis_data:
