"""Notification event names and preference mapping."""

from __future__ import annotations

from typing import Final

EVENT_BACKTEST_COMPLETED: Final[str] = "BACKTEST_COMPLETED"
EVENT_DEPLOYMENT_STARTED: Final[str] = "DEPLOYMENT_STARTED"
EVENT_POSITION_OPENED: Final[str] = "POSITION_OPENED"
EVENT_POSITION_CLOSED: Final[str] = "POSITION_CLOSED"
EVENT_TRADE_APPROVAL_REQUESTED: Final[str] = "TRADE_APPROVAL_REQUESTED"
EVENT_TRADE_APPROVAL_APPROVED: Final[str] = "TRADE_APPROVAL_APPROVED"
EVENT_TRADE_APPROVAL_REJECTED: Final[str] = "TRADE_APPROVAL_REJECTED"
EVENT_TRADE_APPROVAL_EXPIRED: Final[str] = "TRADE_APPROVAL_EXPIRED"
EVENT_RISK_TRIGGERED: Final[str] = "RISK_TRIGGERED"
EVENT_EXECUTION_ANOMALY: Final[str] = "EXECUTION_ANOMALY"

SUPPORTED_NOTIFICATION_EVENTS: Final[frozenset[str]] = frozenset(
    {
        EVENT_BACKTEST_COMPLETED,
        EVENT_DEPLOYMENT_STARTED,
        EVENT_POSITION_OPENED,
        EVENT_POSITION_CLOSED,
        EVENT_TRADE_APPROVAL_REQUESTED,
        EVENT_TRADE_APPROVAL_APPROVED,
        EVENT_TRADE_APPROVAL_REJECTED,
        EVENT_TRADE_APPROVAL_EXPIRED,
        EVENT_RISK_TRIGGERED,
        EVENT_EXECUTION_ANOMALY,
    }
)

MANDATORY_NOTIFICATION_EVENTS: Final[frozenset[str]] = frozenset(
    {
        EVENT_TRADE_APPROVAL_REQUESTED,
        EVENT_TRADE_APPROVAL_APPROVED,
        EVENT_TRADE_APPROVAL_REJECTED,
        EVENT_TRADE_APPROVAL_EXPIRED,
    }
)

EVENT_TO_PREFERENCE_FIELD: Final[dict[str, str]] = {
    EVENT_BACKTEST_COMPLETED: "backtest_completed_enabled",
    EVENT_DEPLOYMENT_STARTED: "deployment_started_enabled",
    EVENT_POSITION_OPENED: "position_opened_enabled",
    EVENT_POSITION_CLOSED: "position_closed_enabled",
    EVENT_RISK_TRIGGERED: "risk_triggered_enabled",
    EVENT_EXECUTION_ANOMALY: "execution_anomaly_enabled",
}
