#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

PROFILE="dev"
OUTPUT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --output)
      OUTPUT="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 1
      ;;
  esac
done

COMMON_FILE="${BACKEND_DIR}/env/.env.common"
PROFILE_FILE="${BACKEND_DIR}/env/.env.${PROFILE}"

if [[ -z "${OUTPUT}" ]]; then
  OUTPUT="${BACKEND_DIR}/.env.${PROFILE}"
fi

if [[ ! -f "${COMMON_FILE}" ]]; then
  echo "Missing ${COMMON_FILE}. Copy from env/.env.common.example first." >&2
  exit 1
fi
if [[ ! -f "${PROFILE_FILE}" ]]; then
  echo "Missing ${PROFILE_FILE}. Copy from env/.env.${PROFILE}.example first." >&2
  exit 1
fi

INPUTS=(
  "${COMMON_FILE}"
  "${PROFILE_FILE}"
)

COMMON_LOCAL="${BACKEND_DIR}/env/.env.common.local"
PROFILE_LOCAL="${BACKEND_DIR}/env/.env.${PROFILE}.local"
if [[ -f "${COMMON_LOCAL}" ]]; then
  INPUTS+=("${COMMON_LOCAL}")
fi
if [[ -f "${PROFILE_LOCAL}" ]]; then
  INPUTS+=("${PROFILE_LOCAL}")
fi

mkdir -p "$(dirname -- "${OUTPUT}")"

{
  printf '# Generated by scripts/render_env.sh (%s UTC)\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  awk -F= '
    /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
    {
      key=$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
      lines[key]=$0
      order[++n]=key
    }
    END {
      for (i = 1; i <= n; i++) {
        key=order[i]
        if (!printed[key]++) {
          print lines[key]
        }
      }
    }
  ' "${INPUTS[@]}"
} > "${OUTPUT}"

echo "Rendered env file: ${OUTPUT}"
