"""Pre-trade approval request model."""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING
from uuid import UUID

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.models.base import Base

if TYPE_CHECKING:
    from src.models.deployment import Deployment
    from src.models.order import Order
    from src.models.user import User


class TradeApprovalRequest(Base):
    """One open-order approval request generated by runtime."""

    __tablename__ = "trade_approval_requests"
    __table_args__ = (
        CheckConstraint(
            "signal IN ('OPEN_LONG', 'OPEN_SHORT')",
            name="ck_trade_approval_requests_signal",
        ),
        CheckConstraint(
            "side IN ('long', 'short')",
            name="ck_trade_approval_requests_side",
        ),
        CheckConstraint("qty > 0", name="ck_trade_approval_requests_qty_positive"),
        CheckConstraint("mark_price >= 0", name="ck_trade_approval_requests_mark_price_non_negative"),
        CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'expired', "
            "'executing', 'executed', 'failed', 'cancelled')",
            name="ck_trade_approval_requests_status",
        ),
        CheckConstraint(
            "approval_channel IN ('telegram', 'discord', 'slack', 'whatsapp')",
            name="ck_trade_approval_requests_approval_channel",
        ),
        CheckConstraint(
            "approved_via IS NULL OR approved_via IN ('telegram', 'api', 'system')",
            name="ck_trade_approval_requests_approved_via",
        ),
        UniqueConstraint(
            "approval_key",
            name="uq_trade_approval_requests_approval_key",
        ),
        Index(
            "ix_trade_approval_requests_status_expires",
            "status",
            "expires_at",
        ),
        Index(
            "ix_trade_approval_requests_deployment_status_requested",
            "deployment_id",
            "status",
            "requested_at",
        ),
    )

    user_id: Mapped[UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    deployment_id: Mapped[UUID] = mapped_column(
        ForeignKey("deployments.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    execution_order_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("orders.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    signal: Mapped[str] = mapped_column(String(16), nullable=False)
    side: Mapped[str] = mapped_column(String(16), nullable=False)
    symbol: Mapped[str] = mapped_column(String(80), nullable=False, index=True)
    qty: Mapped[Decimal] = mapped_column(Numeric(20, 8), nullable=False)
    mark_price: Mapped[Decimal] = mapped_column(Numeric(20, 8), nullable=False)
    reason: Mapped[str] = mapped_column(String(255), nullable=False)
    timeframe: Mapped[str] = mapped_column(String(32), nullable=False)
    bar_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    approval_channel: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        default="telegram",
        server_default="telegram",
    )
    approval_key: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    intent_payload: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
    )
    metadata_: Mapped[dict] = mapped_column(
        "metadata",
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="pending",
        server_default="pending",
    )
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
        index=True,
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    approved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    rejected_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    expired_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    executed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    approved_via: Mapped[str | None] = mapped_column(String(20), nullable=True)
    decision_actor: Mapped[str | None] = mapped_column(String(128), nullable=True)
    execution_error: Mapped[str | None] = mapped_column(Text, nullable=True)

    user: Mapped[User] = relationship(back_populates="trade_approval_requests")
    deployment: Mapped[Deployment] = relationship(back_populates="trade_approval_requests")
    execution_order: Mapped[Order | None] = relationship()
